In [1]:
#Q1) State differences between Numpy Array and lists.
#Arrays are homogeneous where as Lists can be homogeneous or heterogeneous
#Element wise operation is possible in arrays but not possible in lists
#Arrays are very useful for multi-dimensional data.

In [4]:
#Q2) Write a Code to create 50 evenly spaced numbers between 0 to 10.
import numpy as np
x1 = np.linspace(0,10,50)
x1

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [6]:
#Q3) Write a Code to create an array of shape (4,5) with random samples with random seed 7.
np.random.seed(7)
arr = np.random.random((4,5))
arr

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518, 0.97798951],
       [0.53849587, 0.50112046, 0.07205113, 0.26843898, 0.4998825 ],
       [0.67923   , 0.80373904, 0.38094113, 0.06593635, 0.2881456 ],
       [0.90959353, 0.21338535, 0.45212396, 0.93120602, 0.02489923]])

In [7]:
#Q4) Write a Code to reshape the array created in Q3 into shape (2,10).
arr = arr.reshape(2,10)
arr

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518, 0.97798951,
        0.53849587, 0.50112046, 0.07205113, 0.26843898, 0.4998825 ],
       [0.67923   , 0.80373904, 0.38094113, 0.06593635, 0.2881456 ,
        0.90959353, 0.21338535, 0.45212396, 0.93120602, 0.02489923]])

In [15]:
#Q5) Create an 1D array starting from 0 ending with 100 with stepsize 10 and
#another array starting from 1000 ending with 10000 with stepsize 1000 and
#then concatenate two arrays created.
x1 = np.arange(0,100+10,10)
x2 = np.arange(1000,10000+1000,1000)
x3 = np.concatenate([x1,x2])
x3

array([    0,    10,    20,    30,    40,    50,    60,    70,    80,
          90,   100,  1000,  2000,  3000,  4000,  5000,  6000,  7000,
        8000,  9000, 10000])

In [16]:
#Q6) Use array created in Q5 and replace the values lesser than 50 as <50.
np.where(x3<50,'<50',x3)

array(['<50', '<50', '<50', '<50', '<50', '50', '60', '70', '80', '90',
       '100', '1000', '2000', '3000', '4000', '5000', '6000', '7000',
       '8000', '9000', '10000'], dtype='<U11')

In [17]:
#Q7) Write a Code to create 1D, 2D and 3D arrays randomly.
print(np.random.rand(5))
print(np.random.rand(3,2))
print(np.random.rand(3,3,3))

[0.60054892 0.9501295  0.23030288 0.54848992 0.90912837]
[[0.13316945 0.52341258]
 [0.75040986 0.66901324]
 [0.46775286 0.20484909]]
[[[0.49076589 0.37238469 0.47740115]
  [0.36589039 0.83791799 0.76864751]
  [0.31399468 0.57262533 0.27604905]]

 [[0.45284293 0.35297837 0.65739946]
  [0.37035108 0.45909298 0.71932412]
  [0.41299183 0.90642327 0.18045162]]

 [[0.74111887 0.42237404 0.42645357]
  [0.63437987 0.5229062  0.41488598]
  [0.00142688 0.09226235 0.70939439]]]


In [21]:
#Q8) Write a Code to create an array with 10 random integers within 100.
np.random.randint(0,100,10)

array([40, 36, 69, 28, 93, 49, 61, 52, 95,  7])

In [27]:
#Q9) Create a array with an sample data with shape of (5,4) with standard
#    normal distribution with random seed of 201.
np.random.seed(201)
arr = np.random.normal(loc=0,scale=1,size=(5,4))
arr

array([[ 0.31678346, -0.4934171 ,  1.21794581,  0.43677076],
       [-0.72769267,  0.43030744, -0.68666532, -0.45301801],
       [-0.73285921, -0.75362743, -0.83251892,  0.44987187],
       [ 1.80752304, -0.48953136,  0.88158874, -0.69834087],
       [-0.0499747 ,  1.90752236, -0.32762267,  1.15003185]])

In [30]:
#Q10) Use the array from Q9 and create a data frame with index=['L','M','N','O','P'], columns=['A','B','C','D']
import pandas as pd
df = pd.DataFrame(index=['L','M','N','O','P'],columns=['A','B','C','D'],data=arr)
df

A         B         C         D
L  0.316783 -0.493417  1.217946  0.436771
M -0.727693  0.430307 -0.686665 -0.453018
N -0.732859 -0.753627 -0.832519  0.449872
O  1.807523 -0.489531  0.881589 -0.698341
P -0.049975  1.907522 -0.327623  1.150032

In [35]:
#Q11) Find the most frequent value in an numpy 1D array.
#     Use array x = np.array([10,20,66,20,10,30,50,60,70,60,66,12,13,66])
x = np.array([10,20,66,20,10,30,50,60,70,60,66,12,13,66])
np.bincount(x).argmax()

66

In [36]:
#Q12) Write a Code to Flatten a 2d array into 1d array.
#     Use array: np.array()
x4 = np.array([[1,2,3],[8,9,10],[11,22,33]])
x4.flatten()

array([ 1,  2,  3,  8,  9, 10, 11, 22, 33])

In [37]:
#Part II: PANDAS
#About Dataset Provided.
#YouTube Dislikes Dataset: This dataset contains information about trending YouTube videos from August 2020 to December 2021 for the USA, Canada, and Great Britain.
#Context and Content: Youtube announced the decision to hide the number of dislikes from users around November 2021. However, the official YouTube Data API allowed you to get information about dislikes until December 13, 2021.
#This dataset contains the latest possible information about dislikes,likes,views and more which was collected just before December 13. The information was collected by videos that had been trending in the USA, Canada, and Great Britain for a year prior.

In [39]:
#Q1) Import required libraries and read the provided dataset (youtube_dislike_dataset.csv) and retrieve top 5 and bottom 5 records.
import numpy as np
import pandas as pd
df = pd.read_csv('youtube_dislike_dataset.csv')
df.head()

video_id                                       title  \
0  --0bCF-iK2E        Jadon Sancho  Magical Skills & Goals   
1  --14w5SOEUs          Migos - Avalanche (Official Video)   
2  --40TEbZ9Is  Supporting Actress in a Comedy: 73rd Emmys   
3  --4tfbSyYDE     JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO   
4       #NAME?                Why Retaining Walls Collapse   

                 channel_id          channel_title      published_at  \
0  UC6UL29enLNe4mqwTfAyeNuw             Bundesliga  01-07-2021 10:00   
1  UCGIelM2Dj3zza3xyV3pL3WQ              MigosVEVO  10-06-2021 16:00   
2  UClBKH8yZRcM4AsRjDVEdjMg     Television Academy  20-09-2021 01:03   
3  UCsmXiDP8S40uBeJYxvyulmA                    JO1  03-03-2021 10:00   
4  UCMOqf8ab-42UUQIdVoKwjlQ  Practical Engineering  07-12-2021 13:00   

   view_count   likes  dislikes  comment_count  \
0     1048888   19515       226           1319   
1    15352638  359277      7479          18729   
2      925281   11212       401            831   
3     2641597   39131       441           3745   
4      715724   32887       367           1067   

                                                tags  \
0  football soccer ftbol alemn Bundesliga season ...   
1  Migos Avalanche Quality Control Music/Motown R...   
2                                                      
3  PRODUCE101JAPAN              JO1   TheSTAR STA...   
4  retaining wall New Jersey highway Direct Conne...   

                                         description  \
0  Enjoy the best skills and goals from Jadon San...   
1  Watch the the official video for Migos - "Aval...   
2  Hannah Waddingham wins the Emmy for Supporting...   
3  JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO\n\n---...   
4  One of the most important (and innocuous) part...   

                                            comments  
0  Respect to Dortmund fans,must be sad losing hi...  
1  Migos just makes me want to live my live to th...  
2  Hannah's energy bursts through any screen. Wel...  
3  youngVer><  REN is really PERFECT. It's not ju...  
4   Keep up with all my projects here: https://pr...

In [40]:
df.tail()

video_id                                              title  \
37417  zzd4ydafGR0  Lil Tjay - Calling My Phone (feat. 6LACK) [Off...   
37418  zziBybeSAtw  PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...   
37419  zzk09ESX7e0                 [MV]  (MAMAMOO) - Where Are We Now   
37420  zzmQEb0Em5I              FELLIPE ESCUDERO- Master Podcast  #12   
37421  zzxPZwaA-8w  Gareth Bale brace secures dramatic comeback on...   

                     channel_id      channel_title      published_at  \
37417  UCEB4a5o_6KfjxHwNMnmj54Q           Lil Tjay  12-02-2021 05:03   
37418  UCWJ2lWNubArHWmf3FIHbfcQ                NBA  16-01-2021 05:39   
37419  UCuhAUMLzJxlP1W7mEk0_6lA            MAMAMOO  02-06-2021 09:00   
37420  UC8NjnNWMsRqq11NYvHAQb1g     Master Podcast  20-10-2020 20:59   
37421  UCEg25rdRZXg32iwai6N6l0w  Tottenham Hotspur  23-05-2021 21:00   

       view_count    likes  dislikes  comment_count  \
37417   120408275  2180780     35871          81360   
37418     2841917    20759      1049           2624   
37419    13346678   720854      4426          90616   
37420      252057    19198      1234           1471   
37421     2252090    34063       868           2004   

                                                    tags  \
37417  Lil Tjay Steady Calling My Phone Calling My Ph...   
37418  NBA G League Basketball game-0022000187 Lakers...   
37419  MAMAMOO  WAW  WAW MAMAMOO WAW Where Are We Now...   
37420  master masterpodcast lord lord vinheteiro z z ...   
37421  Spurs Tottenham Hotspur   Tottenham Leicester ...   

                                             description  \
37417  Official video for "Calling My Phone" by Lil T...   
37418  PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...   
37419  [MV]  (MAMAMOO) - Where Are We Now\n\nInstagra...   
37420  DOCTOR HAIR\nhttps://www.thedoctorhair.com/?fb...   
37421  Two minute highlights from Tottenham Hotspur's...   

                                                comments  
37417  'DESTINED 2 WIN' OUT NOW !! https://liltjay.ln...  
37418  Montrezl Harrell is going crazy with the rebou...  
37419  I honestly do not know why this song hit so ha...  
37420  Foi um prazer passar esta tarde com vocs debat...  
37421  Thank you Kane for everything you have given t...

In [41]:
#Q2) Check the info of the data frame and write your inferences on datatypes and shape of the dataset.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37422 entries, 0 to 37421
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   video_id       37422 non-null  object
 1   title          37422 non-null  object
 2   channel_id     37422 non-null  object
 3   channel_title  37422 non-null  object
 4   published_at   37422 non-null  object
 5   view_count     37422 non-null  int64 
 6   likes          37422 non-null  int64 
 7   dislikes       37422 non-null  int64 
 8   comment_count  37422 non-null  int64 
 9   tags           37422 non-null  object
 10  description    37422 non-null  object
 11  comments       37264 non-null  object
dtypes: int64(4), object(8)
memory usage: 3.4+ MB


In [42]:
df.shape

(37422, 12)

In [43]:
#Inference
#There are 12 columns and 37422 rows.
#There are 8 columns datatypes as object and rest all are integer datatype.
#We can consider column video_id as unique identifier for all the rows.
#We can convert column published_at to pandas date_time format.
#We can observe some null values in the column comments.

In [47]:
#Q3) Check for the Percentage of the Null values and drop it.
round(df.isnull().sum()/len(df)*100,2)

video_id         0.00
title            0.00
channel_id       0.00
channel_title    0.00
published_at     0.00
view_count       0.00
likes            0.00
dislikes         0.00
comment_count    0.00
tags             0.00
description      0.00
comments         0.42
dtype: float64

In [48]:
df = df.dropna()
df

video_id                                              title  \
0      --0bCF-iK2E               Jadon Sancho  Magical Skills & Goals   
1      --14w5SOEUs                 Migos - Avalanche (Official Video)   
2      --40TEbZ9Is         Supporting Actress in a Comedy: 73rd Emmys   
3      --4tfbSyYDE            JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO   
4           #NAME?                       Why Retaining Walls Collapse   
...            ...                                                ...   
37417  zzd4ydafGR0  Lil Tjay - Calling My Phone (feat. 6LACK) [Off...   
37418  zziBybeSAtw  PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...   
37419  zzk09ESX7e0                 [MV]  (MAMAMOO) - Where Are We Now   
37420  zzmQEb0Em5I              FELLIPE ESCUDERO- Master Podcast  #12   
37421  zzxPZwaA-8w  Gareth Bale brace secures dramatic comeback on...   

                     channel_id          channel_title      published_at  \
0      UC6UL29enLNe4mqwTfAyeNuw             Bundesliga  01-07-2021 10:00   
1      UCGIelM2Dj3zza3xyV3pL3WQ              MigosVEVO  10-06-2021 16:00   
2      UClBKH8yZRcM4AsRjDVEdjMg     Television Academy  20-09-2021 01:03   
3      UCsmXiDP8S40uBeJYxvyulmA                    JO1  03-03-2021 10:00   
4      UCMOqf8ab-42UUQIdVoKwjlQ  Practical Engineering  07-12-2021 13:00   
...                         ...                    ...               ...   
37417  UCEB4a5o_6KfjxHwNMnmj54Q               Lil Tjay  12-02-2021 05:03   
37418  UCWJ2lWNubArHWmf3FIHbfcQ                    NBA  16-01-2021 05:39   
37419  UCuhAUMLzJxlP1W7mEk0_6lA                MAMAMOO  02-06-2021 09:00   
37420  UC8NjnNWMsRqq11NYvHAQb1g         Master Podcast  20-10-2020 20:59   
37421  UCEg25rdRZXg32iwai6N6l0w      Tottenham Hotspur  23-05-2021 21:00   

       view_count    likes  dislikes  comment_count  \
0         1048888    19515       226           1319   
1        15352638   359277      7479          18729   
2          925281    11212       401            831   
3         2641597    39131       441           3745   
4          715724    32887       367           1067   
...           ...      ...       ...            ...   
37417   120408275  2180780     35871          81360   
37418     2841917    20759      1049           2624   
37419    13346678   720854      4426          90616   
37420      252057    19198      1234           1471   
37421     2252090    34063       868           2004   

                                                    tags  \
0      football soccer ftbol alemn Bundesliga season ...   
1      Migos Avalanche Quality Control Music/Motown R...   
2                                                          
3      PRODUCE101JAPAN              JO1   TheSTAR STA...   
4      retaining wall New Jersey highway Direct Conne...   
...                                                  ...   
37417  Lil Tjay Steady Calling My Phone Calling My Ph...   
37418  NBA G League Basketball game-0022000187 Lakers...   
37419  MAMAMOO  WAW  WAW MAMAMOO WAW Where Are We Now...   
37420  master masterpodcast lord lord vinheteiro z z ...   
37421  Spurs Tottenham Hotspur   Tottenham Leicester ...   

                                             description  \
0      Enjoy the best skills and goals from Jadon San...   
1      Watch the the official video for Migos - "Aval...   
2      Hannah Waddingham wins the Emmy for Supporting...   
3      JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO\n\n---...   
4      One of the most important (and innocuous) part...   
...                                                  ...   
37417  Official video for "Calling My Phone" by Lil T...   
37418  PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...   
37419  [MV]  (MAMAMOO) - Where Are We Now\n\nInstagra...   
37420  DOCTOR HAIR\nhttps://www.thedoctorhair.com/?fb...   
37421  Two minute highlights from Tottenham Hotspur's...   

                                                comments  
0      Respect to Dortmund fans,must be sad losing hi...  

In [49]:
df.shape

(37264, 12)

In [50]:
#Q4) Check the statistical summary of the dataset.
df.describe()

view_count         likes      dislikes  comment_count
count  3.726400e+04  3.726400e+04  3.726400e+04   3.726400e+04
mean   5.710821e+06  1.672867e+05  4.996434e+03   9.966953e+03
std    2.431304e+07  5.384931e+05  3.075194e+04   1.173465e+05
min    2.036800e+04  2.200000e+01  3.000000e+00   1.000000e+00
25%    5.141305e+05  1.331725e+04  2.827500e+02   9.140000e+02
50%    1.321860e+06  4.255600e+04  7.980000e+02   2.347000e+03
75%    3.674527e+06  1.309665e+05  2.466250e+03   6.212000e+03
max    1.322797e+09  3.183768e+07  2.397733e+06   1.607103e+07

In [51]:
#Q5) Convert datatype of column published_at from object to pandas datetime.
df['published_at'] = pd.to_datetime(df['published_at'])
df[['published_at']].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37264 entries, 0 to 37421
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   published_at  37264 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 582.2 KB


In [53]:
#Q6) Create a column as 'published_month' using the column published_at.
df['published_month'] = df['published_at'].dt.month
df.head(2)

video_id                                 title  \
0  --0bCF-iK2E  Jadon Sancho  Magical Skills & Goals   
1  --14w5SOEUs    Migos - Avalanche (Official Video)   

                 channel_id channel_title        published_at  view_count  \
0  UC6UL29enLNe4mqwTfAyeNuw    Bundesliga 2021-01-07 10:00:00     1048888   
1  UCGIelM2Dj3zza3xyV3pL3WQ     MigosVEVO 2021-10-06 16:00:00    15352638   

    likes  dislikes  comment_count  \
0   19515       226           1319   
1  359277      7479          18729   

                                                tags  \
0  football soccer ftbol alemn Bundesliga season ...   
1  Migos Avalanche Quality Control Music/Motown R...   

                                         description  \
0  Enjoy the best skills and goals from Jadon San...   
1  Watch the the official video for Migos - "Aval...   

                                            comments  published_month  
0  Respect to Dortmund fans,must be sad losing hi...                1  
1  Migos just makes me want to live my live to th...               10

In [54]:
#Q7) Replace the numbers in column published_month as names of the months i,e., 1 as 'Jan', 2 as 'Feb' and so on.....
df['published_month'] = df['published_month'].replace({1:'Jan',2:'Feb',3:'March',4:'April',5:'May',6:'June',
                                                      7:'July',8:'Aug',9:'Sep',10:'Oct',11:'Nov',12:'Dec'})
df['published_month'].head(4)

0      Jan
1      Oct
2      Sep
3    March
Name: published_month, dtype: object

In [55]:
#Q8) Find the minimum and maximum value of the view_count, likes, dislikes and comment_count and write your inferences.
df[['view_count','likes','dislikes','comment_count']].min(),df[['view_count','likes','dislikes','comment_count']].max()

(view_count       20368
 likes               22
 dislikes             3
 comment_count        1
 dtype: int64,
 view_count       1322796924
 likes              31837675
 dislikes            2397733
 comment_count      16071029
 dtype: int64)

In [58]:
#Q9) Find the count of unique video_id, channel_id and channel_title.
df['video_id'].value_counts()

#NAME?         456
--0bCF-iK2E      1
eqKgFbaD7-E      1
ep4DJCLT3bw      1
ep6O6tEh9Uo      1
              ... 
KdK2ZwrCnbY      1
KdIlvta-yGA      1
Kd7vpW0Czgo      1
Kd6bykDKTyo      1
zzxPZwaA-8w      1
Name: video_id, Length: 36809, dtype: int64

In [59]:
df['channel_id'].value_counts()

UCNAf1k0yIjyGu3k9BwAg3lg    533
UCMmVPVb0BwSIOWVeDwlPocQ    301
UC4i_9WvfPRTuRWEaWyfKuFw    246
UCWJ2lWNubArHWmf3FIHbfcQ    209
UCDVYQ4Zhbm3S2dlz7P1GBDg    162
                           ... 
UC-IVpEe1GQYclVEGLgPd82Q      1
UCGfclwcB8i13_4tp_FJjqbQ      1
UCp5bjkAcMNFo_6HJ3oEGdug      1
UC2Q91pxDF0BPf0eK44pgYMw      1
UC8NjnNWMsRqq11NYvHAQb1g      1
Name: channel_id, Length: 10891, dtype: int64

In [60]:
df['channel_id'].value_counts()

UCNAf1k0yIjyGu3k9BwAg3lg    533
UCMmVPVb0BwSIOWVeDwlPocQ    301
UC4i_9WvfPRTuRWEaWyfKuFw    246
UCWJ2lWNubArHWmf3FIHbfcQ    209
UCDVYQ4Zhbm3S2dlz7P1GBDg    162
                           ... 
UC-IVpEe1GQYclVEGLgPd82Q      1
UCGfclwcB8i13_4tp_FJjqbQ      1
UCp5bjkAcMNFo_6HJ3oEGdug      1
UC2Q91pxDF0BPf0eK44pgYMw      1
UC8NjnNWMsRqq11NYvHAQb1g      1
Name: channel_id, Length: 10891, dtype: int64

In [61]:
#Q10) Find the top10 channel names having the highest number of videos in the dataset and the bottom10 having lowest number of videos.
df.groupby('channel_title')['video_id'].count().sort_values(ascending=False).head(10)

channel_title
Sky Sports Football    533
The United Stand       301
BT Sport               246
NBA                    209
NFL                    162
WWE                    122
SSSniperWolf            99
SSundee                 98
FORMULA 1               87
NHL                     86
Name: video_id, dtype: int64

In [64]:
df.groupby('channel_title')['video_id'].count().sort_values(ascending=True).head(10)

channel_title
   SilverName                   1
Mio Channel                     1
Miniatur Wunderland             1
MiniBloxia                      1
Mini Muka                       1
Mini Ladd                       1
MindYourLogic                   1
Mind Body Tonic With Dr Sita    1
Mimi Ar                         1
Millyz                          1
Name: video_id, dtype: int64

In [65]:
#Q11) Find the title of the video which has the maximum number of likes and the title of the video having minimum likes and write your inferences.
pd.pivot_table(df,index=['title'],values=['likes'],aggfunc=np.max).sort_values(by='likes',ascending=False).head(1)

likes
title                                  
BTS () 'Dynamite' Official MV  31837675

In [66]:
pd.pivot_table(df,index=['title'],values=['likes'],aggfunc=np.max).sort_values(by='likes',ascending=True).head(1)

likes
title                               
Leading the Charge | Circle K     22

In [67]:
#Q12) Find the title of the video which has the maximum number of dislikes and the title of the video having minimum dislikes and write your inferences.
pd.pivot_table(df,index=['title'],values=['dislikes'],aggfunc=np.max).sort_values(by='dislikes',ascending=False).head(1)

dislikes
title                                        
Cuties | Official Trailer | Netflix   2397733

In [68]:
pd.pivot_table(df,index=['title'],values=['dislikes'],aggfunc=np.max).sort_values(by='dislikes',ascending=True).head(1)

dislikes
title                                           
Tims For Good: A Taste Of The Familiar         3